#!/usr/bin/env bash
# Takes a subdomain and a domain and returns information about the subdomain

print_info () {
    subdomain="$1"
    domain="$2"
    output=$(dig +short "$subdomain")
    
    if [ -n "$output" ]; then
        record_type=$(echo "$output" | awk '{print $1}')
        record_value=$(echo "$output" | awk '{print $2}')
        
        echo "The subdomain $subdomain is a $record_type record and points to $record_value"
    else
        echo "The subdomain $subdomain does not exist."
    fi
}

if [ "$#" -eq 2 ]; then
    print_info "$2.$1" "$2"
else
    print_info "www.$1" "www"
    print_info "lb-01.$1" "lb-01"
    print_info "web-01.$1" "web-01"
    print_info "web-02.$1" "web-02"
fi
