#!/usr/bin/env bash
# This script diplsyas list of currently running processes
# must show all processes, for all users, including those which might not have a TTY
# display a user-orientated format
# show process hierarchy

ps -a -x -u -f
