#!/usr/bin/env bash
# This script extends previous exercise command and displays line containing bash word, this allowing you to easily get PID of bash process
# You cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
