#!/usr/bin/env bash
# displays Best School 10 times.

REPEAT=10

for ((i = 1; i <= REPEAT; i++)); do
    COUNTER=1
    while [ $COUNTER -lt 101 ]; do
        if [ $((COUNTER % 15)) = 0 ]; then
            echo "FizzBuzz"
        elif [ $((COUNTER % 3)) = 0 ]; then
            echo "Fizz"
        elif [ $((COUNTER % 5)) = 0 ]; then
            echo "Buzz"
        else
            echo "$COUNTER"
        fi
        let COUNTER+=1
    done
done
