#!/usr/bin/env bash
# loops from 1 to 10 and displays "bad luck" for the 4th iteration,
# "good luck" for the 8th iteration, and "best School" for others

k=1

while [ $k -le 10 ]; do
        if [ $k -eq 4 ]; then
                echo "bad luck"
        elif [ $k -eq 8 ]; then
                echo "good luck"
        else
                echo "Best School"
        fi
        k=$((k+1))
done
